### ISSUE TITLE
App freezes

### ISSUE THREAD

**Issue by Hobbe81** [filecoin-station/desktop#1659] opened 2024-07-01 12:12 UTC
When I start my computer it automatically logs in. Then it asks for the password to unlock the keyring.
If I don't enter it and leave the computer it will lock the screen and then when I try to type in my password there it will try to unlock the screen but it can't.
So I have to press the logout button to where I can login to my desktop but then Filecoin Station is messed up and won't work even if I reboot.

Only fix is to delete the station_id file but that changes my wallet so funds are lost.

This is on Linux Mint 21.3

**Comment by bajtos** [comment] 2024-07-01 12:24
I think the problem was introduced by https://github.com/filecoin-station/desktop/pull/1497, where we use the wallet's private key to derive the passphrase for Station Core to encrypt the StationID identity file.

We need to change this part to handle the case when the wallet cannot be initialised because the keyring has not been unlocked yet.

**Comment by bajtos** [comment] 2024-07-01 12:50
<img width="930" alt="Screenshot 2024-07-01 at 14 50 01" src="https://github.com/filecoin-station/desktop/assets/1140553/2692b86d-1c6e-493d-bcf9-d6f7f3745b22">

<img width="466" alt="Screenshot 2024-07-01 at 14 50 47" src="https://github.com/filecoin-station/desktop/assets/1140553/aed5f255-2ecb-40b7-9ca2-b5b7c202bc81">

**Comment by bajtos** [comment] 2024-07-03 14:09
@Hobbe81 I am not able to reproduce this problem 😢 

When I start the Station and don't grant it access to the keychain (on my MacOS), it shows an error dialog and DOES NOT proceed to start Station Core or derive the passphrase from the private wallet key.

When I restart the Station and grant it access to the keychain, it loads the seed phrase and reconstructs the private wallet key and the passphrase, and everything works correctly.

@Hobbe81 What desktop environment do you use on your Linux Mint installation? Is it Gnome or something else?

@juliangruber Do you have a machine where you can install Linux Mint and try to reproduce this problem?

**Comment by juliangruber** [comment] 2024-07-03 14:40
> If I don't enter it and leave the computer it will lock the screen and then when I try to type in my password there it will try to unlock the screen but it can't.

It looks like this is a problem with your window manager - if your screen locks while there's an opened password dialog, you can't log back into the machine. Is that right?

**Comment by Hobbe81** [comment] 2024-07-03 15:17
Yes, that's right.

Den ons 3 juli 2024 16:40Julian Gruber ***@***.***> skrev:

**Comment by juliangruber** [comment] 2024-07-03 15:45
This is out of scope for us then. Your desktop should either be set up so that it remembers that you will grant access to the secrets store, or not break if it goes to sleep. There's nothing we can do here.

**Closed by juliangruber** 2024-07-03 15:45 UTC
Labels: bug :bug:
